// Generated by Selenium IDE
package googleloading;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BOOKFROMAMAZONTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void bOOKFROMAMAZON() {
    driver.get("https://www.google.com/search?q=BOOKS&sca_esv=569046937&sxsrf=AM9HkKloFX7SelwLFmmrh4Xfcbx856QIJA%3A1695877242318&source=hp&ei=eggVZfGZEYC8seMPkcmXgA0&iflsig=AO6bgOgAAAAAZRUWisw4UBVBP3SPbq2wVjis1PcJRAnf&ved=0ahUKEwjxvu-Ew8yBAxUAXmwGHZHkBdAQ4dUDCAo&uact=5&oq=BOOKS&gs_lp=Egdnd3Mtd2l6IgVCT09LUzIHECMYigUYJzIIEAAYgAQYsQMyCBAAGIAEGLEDMggQABiABBixAzIIEAAYgAQYsQMyCxAAGIAEGLEDGIMBMgcQABiABBgKMgUQABiABDIFEAAYgAQyBRAAGIAESIcYUJoFWMwRcAB4AJABAJgBwQegAb8SqgELMC4xLjIuMi42LTG4AQPIAQD4AQGoAgrCAgcQIxjqAhgnwgINEC4YxwEY0QMY6gIYJ8ICDRAuGMcBGK8BGOoCGCfCAgQQIxgnwgIIEAAYigUYkQLCAgUQLhiABMICCxAuGIAEGLEDGIMBwgIOEAAYigUYsQMYgwEYkQLCAhEQLhiABBixAxiDARjHARjRA8ICCxAuGIAEGMcBGNEDwgIREAAYigUYsQMYgwEYyQMYkQLCAg4QABiABBixAxiDARiSA8ICCBAAGIoFGJIDwgIIEAAYgAQYkgM&sclient=gws-wiz");
    driver.findElement(By.cssSelector(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.linkText("Sell"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Sell")).click();
    {
      WebElement element = driver.findElement(By.id("nav-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
