// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FlightTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void flight() {
    driver.get("https://www.spicejet.com/");
    driver.findElement(By.cssSelector(".css-1dbjc4n:nth-child(2) > .css-1dbjc4n > .css-1dbjc4n > div:nth-child(1) > .css-1dbjc4n > .css-1dbjc4n > .css-1cwyjr8")).click();
    driver.findElement(By.cssSelector(".css-1dbjc4n:nth-child(2) > .css-1dbjc4n > .css-1dbjc4n > div:nth-child(1) > .css-1dbjc4n > .css-1dbjc4n > .css-1cwyjr8")).sendKeys("ko");
    driver.findElement(By.cssSelector("div:nth-child(3) > .css-1dbjc4n > .css-1dbjc4n > .css-1cwyjr8:nth-child(1)")).sendKeys("dub");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".r-1g94qm0:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".r-1loqt21:nth-child(1) > .r-1b43r93")).click();
    driver.close();
  }
}
