// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.BeforeTest;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OpenksrtcsiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void openksrtcsite() {
    driver.get("https://www.keralartc.com/main.html");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    vars.put("win6045", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6045").toString());
    driver.findElement(By.id("loginSignup")).click();
    driver.findElement(By.cssSelector(".close-wrap > img")).click();
    driver.findElement(By.cssSelector("#fromCity_chosen span")).click();
    driver.findElement(By.cssSelector("#fromCity_chosen input")).sendKeys("my");
    driver.findElement(By.cssSelector(".active-result")).click();
    driver.findElement(By.id("departDate")).click();
    driver.findElement(By.linkText("24")).click();
    driver.findElement(By.id("submitSearch")).click();
    driver.findElement(By.cssSelector(".srch-card:nth-child(4) .selectbutton")).click();
    js.executeScript("window.scrollTo(0,300)");
    driver.findElement(By.cssSelector("div:nth-child(4) > .seatlook:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".points:nth-child(1) .picklabel")).click();
    driver.findElement(By.cssSelector(".col-time")).click();
    driver.findElement(By.cssSelector(".picklabel")).click();
    driver.findElement(By.cssSelector(".point-opt > div:nth-child(1) > div:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".pickups > div:nth-child(2) > div:nth-child(2)")).click();
    driver.findElement(By.name("paxName[0]")).click();
    driver.findElement(By.name("paxName[0]")).sendKeys("devika kp");
    driver.findElement(By.name("paxAge[0]")).click();
    driver.findElement(By.name("paxAge[0]")).sendKeys("23");
    driver.findElement(By.cssSelector("div:nth-child(4) > label:nth-child(2) > span:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".block > .navswitchbtn")).click();
    driver.findElement(By.name("mobileNo")).click();
    driver.findElement(By.name("mobileNo")).sendKeys("7510817157");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("devikakp2013@gmail.com");
    driver.findElement(By.cssSelector(".login-text")).click();
    driver.findElement(By.cssSelector(".referLink")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".submit"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".close-wrap > svg")).click();
  }
}
